### ISSUE TITLE
Change Config of Existing MCS Controller

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#243] opened 2021-02-08 17:21 UTC
From: TA2

Priority: Backlog

Components: Python API

Blockers: None

Currently you pass a config file as an argument to create_controller. However, it would be nice if I could change the config of an existing controller, so I don’t have to recreate it. This would be especially helpful for the integration tests which currently have to create a new controller to test each metadata tier.

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-552

**Comment by bzinberg** [comment] 2021-03-24 21:08
Thanks @ThomasSchellenbergNextCentury.  Here are a couple more feature requests that are orthogonal to the above but fall under the umbrella of "change config":

Currently, the environment variable `$MCS_CONFIG_FILE_PATH` overrides the explicit config argument passed to `create_controller(...)`.  This was the cause of a substantial joint debugging session with @deanwetherby over [Slack](https://machinecommonsense.slack.com/archives/C01R43N0162/p1616196408025200).  If the environment variable stays part of the design, I think the order of precedence should definitely be reversed, interested to hear if you agree/disagree.

It would also be nice to be able to pass in a config object (could be just a dict with certain documented keys) rather than the path to a file -- as a caller I've always been just writing a temp file every time a create a controller.

**Comment by deanwetherby** [comment] 2021-09-30 15:02
Closed by #400

**Closed by deanwetherby** 2021-09-30 15:02 UTC
